### PR TITLE
Community

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Review by dadelson — APPROVED** [review]

**Review by dadelson — APPROVED** [review]

**Review by dadelson — APPROVED** [review]

**Review by dadelson — APPROVED** [review]

**Review by dadelson — APPROVED** [review]

**Comment by corburn** [comment]
It's possible to create default community documents for all repositories:
https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

**Comment by kortschak** [comment]
SGTM. Would you like to send PRs for that?

**Comment by corburn** [comment]
@kortschak it requires creating a public repository named `.github`.

**Comment by kortschak** [comment]
Sorry, I missed that. I will do that soon.

**Comment by kortschak** [comment]
[This](https://github.com/biogo/.github) is the start.

**Comment by dadelson** [comment]
Exciting.

David Adelson
Professor and Chair of Bioinformatics and Computational Genetics
Zhendong Professor for the Molecular Basis of Traditional Chinese Medicine
Postgraduate Coordinator (Genetics)
Co-Director Bioinformatics Hub

Room 261, The Braggs Bldg.
School of Biological Sciences
The University of Adelaide
South Australia, 5005
AUSTRALIA
Ph    : +61 8 8313 7555
Fax   : +61 8 8313 5338

e-mail: david.adelson@adelaide.edu.au
CRICOS Provider Number 00123M
-----------------------------------------------------------
IMPORTANT: This message may contain confidential or legally privileged
information. If you think it was sent to you by mistake, please delete all
copies and advise the sender. For the purposes of the SPAM Act 2003, this
email is authorised by The University of Adelaide.
Think green: read on the screen.



________________________________________

**Pull request merged**
