### PR TITLE
gofmt -s

### PR DESCRIPTION
**Pull request by gordon**
Some code simplifications with `gofmt -s`.

Well, I guess it depends if you still want to support Go 1.3.3. IMHO it should be dropped.

### CODE REVIEW

**Comment by brentp** [comment]
this will break on older version of go.

**Comment by kortschak** [comment]
I'm happy to merge this after 1.6 is released (a couple of weeks); 3 major versions is enough.

**Comment by gordon** [comment]
Cool, makes sense.

**Comment by gordon** [comment]
That was right after the relase :+1:
Thanks!

**Comment by kortschak** [comment]
Thanks for reminding me - I need to add go1.6 and update 1.5.

**Pull request merged**
